# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-fastapi-chart.fullname" . }}
  labels:
    app: {{ include "my-fastapi-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-fastapi-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-fastapi-chart.name" . }}
    spec:
      containers:
      - name: my-fastapi-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
