# Base image
FROM python:3.8.5

# Set working directory
WORKDIR /

# Copy requirements.txt
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the application code
COPY . .

# Expose the port that the FastAPI application will listen on
EXPOSE 8000

# Run the FastAPI application
CMD ["uvicorn", "index:app", "--host", "localhost", "--port", "5050"]
